include:
  - board: xiao_ble//zmk
    shield: mnhttn_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: mnhTTn_left.uf2
  - board: xiao_ble//zmk
    shield: mnhttn_right
    artifact-name: mnhTTn_left.uf2
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: mnhTTn_reset.uf2

